name: Dikin.com
favicon: null
layout_spectrum: 0.02276
typography_spectrum: 0.73825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332a21'
    - '#917b64'
    - '#cec0b3'
    - '#57493c'
    - '#efeae6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
