name: Dikin.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#50393f'
    - '#e1fdd4'
    - '#b65f4b'
    - '#e1907f'
    - '#dfd8d2'
  brandStrength: 0.5908555928617716
  lightness: 0.777761900331825
  saturation: 0.09533631266094744
  rhythmicContrast: 1
purpose: []
