name: Dikin.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332a21'
    - '#917b64'
    - '#cec0b3'
    - '#57493c'
    - '#efeae6'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
